WebUI/Areas/APanel/Controllers/DistrictController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using ERP.WebUI.Controllers;
using Library.Model.Core.Addresses;
using Library.Service.Core.Addresses;
using Library.ViewModel.Core.Addresses;

namespace ERP.WebUI.Areas.APanel.Controllers
{
    public class DistrictController : BaseController
    {
        #region Ctor
        private readonly IDistrictService _districtService;
        public DistrictController(IDistrictService districtService)
        {
            _districtService = districtService;
        }
        #endregion

        #region Get
        public ActionResult Index(string divisionId)
        {
            try
            {
                if (!string.IsNullOrEmpty(divisionId))
                {
                    var model = new List<DistrictViewModel>();
                    var districtData = Mapper.Map<IEnumerable<DistrictViewModel>>(_districtService.GetAll());
                    model = districtData.Where(x => x.DivisionId == divisionId).ToList();
                    return View(model);
                }
                return View(Mapper.Map<IEnumerable<DistrictViewModel>>(_districtService.GetAll()));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region JSon
        public JsonResult GetDistrictList(string id)
        {
            return Json(new SelectList(_districtService.GetDistrictList(id), "Value", "Text"), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View(new DistrictViewModel { Active = true, Sequence = _districtService.GetAutoSequence() });
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Create(DistrictViewModel districtvm)
        {
            try
            {
                _districtService.Add(Mapper.Map<District>(districtvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"."}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                return View(Mapper.Map<DistrictViewModel>(_districtService.GetById(id)));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Edit(DistrictViewModel districtvm)
        {
            try
            {
                _districtService.Update(Mapper.Map<District>(districtvm));
                return JavaScript($"ShowResult('{"Data update successfully."}','{"success"}','{"redirect"}','{"../"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion
    }
}

WebUI/Areas/CPanel/Controllers/DistrictController.cs
using AutoMapper;
using ERP.WebUI.Controllers;
using Library.Model.Core.Addresses;
using Library.Service.Core.Addresses;
using Library.ViewModel.Core.Addresses;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ERP.WebUI.Areas.CPanel.Controllers
{
    public class DistrictController : BaseController
    {
        #region Ctor
        private readonly IDistrictService _districtService;
        public DistrictController(IDistrictService districtService)
        {
            _districtService = districtService;
        }
        #endregion

        #region Get
        public ActionResult Index()
        {
            try
            {
                return View(Mapper.Map<IEnumerable<DistrictViewModel>>(_districtService.GetAll()));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region JSon
        public JsonResult GetDistrictList(string id)
        {
            return Json(new SelectList(_districtService.GetDistrictList(id), "Value", "Text"), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View(new DistrictViewModel { Active = true, Sequence = _districtService.GetAutoSequence() });
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Create(DistrictViewModel Districtvm)
        {
            try
            {
                _districtService.Add(Mapper.Map<District>(Districtvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"."}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                return View(Mapper.Map<DistrictViewModel>(_districtService.GetById(id)));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Edit(DistrictViewModel Districtvm)
        {
            try
            {
                _districtService.Update(Mapper.Map<District>(Districtvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"../"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion
    }
}

WebUI/Controllers/DistrictController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Library.Model.Core.Addresses;
using Library.Service.Core.Addresses;
using Library.ViewModel.Core.Addresses;

namespace ERP.WebUI.Controllers
{
    public class DistrictController : BaseController
    {
        #region Ctor
        private readonly IDistrictService _districtService;
        public DistrictController(IDistrictService districtService)
        {
            _districtService = districtService;
        }
        #endregion

        #region Get
        public ActionResult Index()
        {
            try
            {
                return View(Mapper.Map<IEnumerable<DistrictViewModel>>(_districtService.GetAll()));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region JSon
        public JsonResult GetDistrictList(string id)
        {
            return Json(new SelectList(_districtService.GetDistrictList(id), "Value", "Text"), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View(new DistrictViewModel { Active = true, Sequence = _districtService.GetAutoSequence() });
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Create(DistrictViewModel districtvm)
        {
            try
            {
                _districtService.Add(Mapper.Map<District>(districtvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"."}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                return View(Mapper.Map<DistrictViewModel>(_districtService.GetById(id)));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]
        public JavaScriptResult Edit(DistrictViewModel districtvm)
        {
            try
            {
                _districtService.Update(Mapper.Map<District>(districtvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"../"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion
    }
}

WebUI/Views/District/Create.cshtml
@model Library.ViewModel.Core.Addresses.DistrictViewModel
@using ERP.WebUI.Html
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-xl-12">
        <a href="/District" class="btn btn-bg pull-right top-button-back" role="button">Back</a>
    </div>
</div>
@using (Ajax.BeginForm("Create", "District", null, new AjaxOptions { HttpMethod = "POST" }, new { id = "DialogForm" }))
{

<div class="row ">
    <div class="col-xl-12">
        <div class="card ">
            <div class="card-header District_tittle">Add District</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Code, new { @class = "control-label   mendatory" })
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Code, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label   mendatory" })
                            @Html.TextBoxFor(model => model.Name, new { autofocus = "", @class = "form-control", placeholder = "District name" })
                            @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="control-label   mendatory ">Country</label>
                            @Html.SimpleDropDownFor(model => model.CountryId, "/Country/GetCountryListWithId/", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CountryId, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="control-label   mendatory ">Division</label>
                            @Html.CascadingDropDownFor(model => model.DivisionId, "/Division/GetDivisionListWithId/", "CountryId", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DivisionId, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, new { @class = "control-label  " })
                            <label>
                                @Html.CheckBoxFor(model => model.Active)
                            </label>
                        </div>
                        <div class="row">
                            <div class="offset-xl-10 col-xl-2">
                                <div class="form-group input-group">
                                    <button type="submit" class="btn btn-bg pull-right">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

                

                    }
                    @section Scripts {@Scripts.Render("~/bundles/jqueryval")
                    <script type="text/javascript">
                        $(function () {

                        });
                    </script>
                    }

                    

WebUI/Views/District/Edit.cshtml
@model Library.ViewModel.Core.Addresses.DistrictViewModel
@using ERP.WebUI.Html
@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col-xl-12">
        <a href="/District" class="btn btn-bg pull-right top-button-back" role="button">Back</a>
        <h4 class="page-header">Update District</h4>
    </div>
</div>
@using (Ajax.BeginForm("Edit", "District", null, new AjaxOptions { HttpMethod = "POST" }, new { id = "DialogForm" }))
{       
    @Html.HiddenFor(model => model.Id)           
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Code, new { @class = "control-label   mendatory" })
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label   mendatory" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "District name" })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label   mendatory ">Country</label>
                @Html.SimpleDropDownFor(model => model.CountryId, "/Country/GetCountryListWithId/", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label   mendatory ">Division</label>
                @Html.CascadingDropDownFor(model => model.DivisionId, "/Division/GetDivisionListWithId/", "CountryId", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DivisionId, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Active, new { @class = "control-label  " })
                <label>
                    @Html.CheckBoxFor(model => model.Active)
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="form-group text-right">
                <div class="col-xl-12">
                    <button type="submit" class="btn btn-bg btn_save">Save</button>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {@Scripts.Render("~/bundles/jqueryval")<script type="text/javascript">
    $(function () {
        
    });
</script>}

WebUI/Views/District/Index.cshtml
@model IEnumerable<Library.ViewModel.Core.Addresses.DistrictViewModel>
@using ERP.WebUI.Html
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-xl-12">
        <div class="top-button">
            <a href="/District/Create" class="btn btn-bg" role="button">Add New</a>
            <a href="/Home" class="btn btn-bg pull-right" role="button">Back</a>
            <hr />
        </div>
    </div>
</div>
@using (Html.BeginForm("Index", "ProductBasicConfiguration", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label ">District Information</label>
                @Html.SimpleDropDown("productBasicConfigurationCategoryId", "/ProductBasicConfigurationCategory/GetConfigurationCategoryList/", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class=" submit-button">
                    <button type="submit" class="btn btn-bg">Show</button>
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-xl-12">
        <div class="panel panel-default card">
            <div class="card-header District_tittle">District Information</div>
            <div class="panel-body card-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead class="thead-heading">
                            <tr>
                                <th>Sequence</th>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var district in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelDistrict => district.Sequence)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelDistrict => district.Code)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelDistrict => district.Name)
                                    </td>
                                    <td>
                                        @Html.YesNoFor(modelItem => district.Active)
                                    </td>
                                    <td>
                                        @Html.ActionLink(" ", "Edit", new { id = district.Id }, new { @class = "btn-sm btn-bg fa fa-edit" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {

        });
    </script>
}