WebUI/Areas/APanel/Controllers/RackController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using ERP.WebUI.Controllers;
using Library.Model.Inventory.Products;
using Library.Service.Inventory.Products;
using Library.ViewModel.Inventory.Products;

namespace ERP.WebUI.Areas.APanel.Controllers
{
    public class RackController : BaseController
    {
        #region Ctor
        private readonly IRackService _rackService;
        public RackController(IRackService rackService)
        {
            _rackService = rackService;
        }
        #endregion

        #region Get
        public ActionResult Index()
        {
            try
            {
                return View(Mapper.Map<IEnumerable<RackViewModel>>(_rackService.GetAll()));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region JSon
        public JsonResult GetRackList()
        {
            try
            {
                return Json(new SelectList(_rackService.Lists(), "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        #endregion

        #region Create
        [HttpGet]

        public ActionResult Create()
        {
            try
            {
                return View(new RackViewModel { Active = true });
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]

        public JavaScriptResult Create(RackViewModel rackvm)
        {
            try
            {
                _rackService.Add(Mapper.Map<Rack>(rackvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"/APanel/Rack"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region Edit

        [HttpGet]

        public ActionResult Edit(string id)
        {
            try
            {
                return View(Mapper.Map<RackViewModel>(_rackService.GetById(id)));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]

        public JavaScriptResult Edit(RackViewModel rackvm)
        {
            try
            {
                _rackService.Update(Mapper.Map<Rack>(rackvm));
                return JavaScript(
                    $"ShowResult('{"Data updated successfully."}','{"success"}','{"redirect"}','{"/APanel/Rack"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion
    }
}

WebUI/Controllers/RackController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Library.Model.Inventory.Products;
using Library.Service.Inventory.Products;
using Library.ViewModel.Inventory.Products;

namespace ERP.WebUI.Controllers
{
    public class RackController : BaseController
    {
        #region Ctor
        private readonly IRackService _rackService;
        public RackController(IRackService rackService)
        {
            _rackService = rackService;
        }
        #endregion

        #region Get
        public ActionResult Index()
        {
            try
            {
                return View(Mapper.Map<IEnumerable<RackViewModel>>(_rackService.GetAll()));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region JSon
        public JsonResult GetRackList()
        {
            try
            {
                return Json(new SelectList(_rackService.Lists(), "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        #endregion

        #region Create
        [HttpGet]

        public ActionResult Create()
        {
            try
            {
                return View(new RackViewModel { Active = true });
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]

        public JavaScriptResult Create(RackViewModel rackvm)
        {
            try
            {
                _rackService.Add(Mapper.Map<Rack>(rackvm));
                return JavaScript($"ShowResult('{"Data saved successfully."}','{"success"}','{"redirect"}','{"/Rack"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion

        #region Edit

        [HttpGet]

        public ActionResult Edit(string id)
        {
            try
            {
                return View(Mapper.Map<RackViewModel>(_rackService.GetById(id)));
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        [HttpPost]

        public JavaScriptResult Edit(RackViewModel rackvm)
        {
            try
            {
                _rackService.Update(Mapper.Map<Rack>(rackvm));
                return JavaScript(
                    $"ShowResult('{"Data updated successfully."}','{"success"}','{"redirect"}','{"/Rack"}')");
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }
        #endregion
    }
}

WebUI/Views/Rack/Create.cshtml
@model Library.ViewModel.Inventory.Products.RackViewModel
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-xl-12">
        <div class="d-flex justify-content-end pb-1">
            <a href="/Rack" class="btn btn-bg" role="button">Back</a>
        </div>
    </div>
</div>
@using (Ajax.BeginForm("Create", "Rack", null, new AjaxOptions { HttpMethod = "POST" }, new { id = "DialogForm" }))
{
    <div class="row ">
        <div class="col-xl-12">
            <div class="card ">
                <div class="card-header Rack_tittle">Add Rack</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Code, new { @class = "control-label   mendatory" })
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control", type = "number" })
                                @Html.ValidationMessageFor(model => model.Code, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, new { @class = "control-label   mendatory" })
                                @Html.TextBoxFor(model => model.Name, new { autofocus = "", @class = "form-control", placeholder = "Rack name" })
                                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label  " })
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Write something ......" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Active, new { @class = "control-label  " })
                                @Html.CheckBoxFor(model => model.Active)
                            </div>
                            <div class="row">
                                <div class="offset-xl-10 col-xl-2">
                                    <div class="form-group input-group">
                                        <button type="submit" class="btn btn-bg pull-right">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {

        });
    </script>
}

WebUI/Views/Rack/Edit.cshtml
@model Library.ViewModel.Inventory.Products.RackViewModel
@{
    ViewBag.Title = "Edit";
}
    <div class="row">
        <div class="col-xl-12">
            <div class="d-flex justify-content-end pb-1">
                <a href="/Rack" class="btn btn-bg" role="button">Back</a>
            </div>
            <hr />
        </div>
    </div>
@using (Ajax.BeginForm("Edit", "Rack", null, new AjaxOptions { HttpMethod = "POST" }, new { id = "DialogForm" }))
{
    @Html.HiddenFor(model => model.Id)
<div class="row ">
    <div class="col-xl-12">
        <div class="card ">
            <div class="card-header Rack_tittle">Update Rack</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Code, new { @class = "control-label   mendatory" })
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control", type = "number" })
                            @Html.ValidationMessageFor(model => model.Code, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label   mendatory" })
                            @Html.TextBoxFor(model => model.Name, new { autofocus = "", @class = "form-control", placeholder = "Rack name" })
                            @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, new { @class = "control-label  " })
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Write something ......" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, new { @class = "control-label  " })
                            @Html.CheckBoxFor(model => model.Active)
                        </div>
                        <div class="row">
                            <div class="offset-xl-10 col-xl-2">
                                <div class="form-group input-group">
                                    <button type="submit" class="btn btn-bg pull-right">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

                    }
                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                        <script type="text/javascript">
                            $(function () {

                            });
                        </script>
                    }

WebUI/Views/Rack/Index.cshtml
@model IEnumerable<Library.ViewModel.Inventory.Products.RackViewModel>
@using ERP.WebUI.Html
@{
    ViewBag.Title = "Index";
}
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex justify-content-between  pb-1">
                <a href="/Rack/Create" class="btn btn-bg" role="button">Add New</a>
                <a href="/Home" class="btn btn-bg top-button-back float-right" role="button">Back</a>
            </div>
            <hr />
        </div>
    </div>

<div class="row">
    <div class="col-xl-12">
        <div class="panel panel-default card">
            <div class="card-header Rack_tittle">Rack Information</div>
            <div class="panel-body card-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead class="thead-heading">
                            <tr>
                                <th>Sequence</th>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Sequence)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Code)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.YesNoFor(modelItem => item.Active)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn-sm btn-bg fa fa-edit" })
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>