WebUI/Areas/APanel/Controllers/MobileShopPurchaseController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;
using AutoMapper;
using ERP.WebUI.ReportViewer;
using Library.Context.Repositories;
using Library.Service.Inventory.Purchases;
using Library.ViewModel.Inventory.Purchases;
using Microsoft.Reporting.WebForms;

namespace ERP.WebUI.Areas.APanel.Controllers
{
    public class MobileShopPurchaseController : Controller
    {
        #region Ctor
        private readonly IPurchaseService _purchaseService;
        private readonly IRawSqlService _rawSqlService;
        public MobileShopPurchaseController(
            IPurchaseService purchaseService,
            IRawSqlService rawSqlService
            )
        {
            _purchaseService = purchaseService;
            _rawSqlService = rawSqlService;
        }

        #endregion

        #region Rdlc Report
        public ActionResult PurchaseSummary(string companyId, string branchId, string dateFrom, string dateTo, string supplierId)
        {
            try
            {
                if (!string.IsNullOrEmpty(dateFrom))
                {
                    DateTime? dfrom = Convert.ToDateTime(dateFrom);
                    dfrom = new DateTime(dfrom.Value.Year, dfrom.Value.Month, dfrom.Value.Day, 0, 0, 0);
                    dateFrom = dfrom.Value.ToString(CultureInfo.InvariantCulture);
                }
                if (!string.IsNullOrEmpty(dateTo))
                {
                    DateTime? dto = Convert.ToDateTime(dateTo);
                    dto = new DateTime(dto.Value.Year, dto.Value.Month, dto.Value.Day, 23, 59, 59);
                    dateTo = dto.Value.ToString(CultureInfo.InvariantCulture);
                }
                IEnumerable<MobileShopPurchaseViewModel> purchases = new List<MobileShopPurchaseViewModel>();
                if (!string.IsNullOrEmpty(companyId))
                {
                    purchases = Mapper.Map<IEnumerable<MobileShopPurchaseViewModel>>(_rawSqlService.GetAllPurchaseSummary(companyId, branchId, dateFrom, dateTo, supplierId));
                }
                return View(purchases);
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        public ActionResult RdlcReportPurchaseSummary(string companyId, string branchId, string dateFrom, string dateTo, string supplierId)
        {
            try
            {
                if (branchId == "null")
                {
                    branchId = "";
                }
                if (dateFrom == "null")
                {
                    dateFrom = "";
                }
                if (dateTo == "null")
                {
                    dateTo = "";
                }
                if (supplierId == "null")
                {
                    supplierId = "";
                }
                if (!string.IsNullOrEmpty(dateFrom))
                {
                    DateTime? dfrom = Convert.ToDateTime(dateFrom);
                    dfrom = new DateTime(dfrom.Value.Year, dfrom.Value.Month, dfrom.Value.Day, 0, 0, 0);
                    dateFrom = dfrom.Value.ToString(CultureInfo.InvariantCulture);
                }
                if (!string.IsNullOrEmpty(dateTo))
                {
                    DateTime? dto = Convert.ToDateTime(dateTo);
                    dto = new DateTime(dto.Value.Year, dto.Value.Month, dto.Value.Day, 23, 59, 59);
                    dateTo = dto.Value.ToString(CultureInfo.InvariantCulture);
                }
                IEnumerable<MobileShopPurchaseViewModel> purchases = new List<MobileShopPurchaseViewModel>();
                if (!string.IsNullOrEmpty(companyId))
                {
                    purchases = Mapper.Map<IEnumerable<MobileShopPurchaseViewModel>>(_rawSqlService.GetAllPurchaseSummary(companyId, branchId, dateFrom, dateTo, supplierId));
                }
                ReportDataSource rpt = new ReportDataSource("Purchase", purchases);
                RdlcReportViewerWithDate.reportDataSource = rpt;
                string rPath = "RdlcReport/RptPurchaseSummary.rdlc";
                Response.Redirect("~/ReportViewer/RdlcReportViewerWithDate.aspx?rPath=" + rPath + "&dfrom=" + dateFrom + "&dto=" + dateTo + "&companyId=" + companyId + "&branchId=" + branchId);
                return View();
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        } 

        public ActionResult PurchaseList(string companyId, string branchId, string dateFrom, string dateTo, string supplierId)
        {
            try
            {
                if (!string.IsNullOrEmpty(dateFrom))
                {
                    DateTime? dfrom = Convert.ToDateTime(dateFrom);
                    dfrom = new DateTime(dfrom.Value.Year, dfrom.Value.Month, dfrom.Value.Day, 0, 0, 0);
                    dateFrom = dfrom.Value.ToString(CultureInfo.InvariantCulture);
                }
                if (!string.IsNullOrEmpty(dateTo))
                {
                    DateTime? dto = Convert.ToDateTime(dateTo);
                    dto = new DateTime(dto.Value.Year, dto.Value.Month, dto.Value.Day, 23, 59, 59);
                    dateTo = dto.Value.ToString(CultureInfo.InvariantCulture);
                }
                IEnumerable<MobileShopPurchaseDetailViewModel> purchaseDetails = new List<MobileShopPurchaseDetailViewModel>();
                if (!string.IsNullOrEmpty(companyId))
                {
                    purchaseDetails = Mapper.Map<IEnumerable<MobileShopPurchaseDetailViewModel>>(_rawSqlService.GetAllPurchaseDetail(companyId, branchId, dateFrom, dateTo, supplierId));
                }
                return View(purchaseDetails);
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        public ActionResult RdlcReportPurchaseList(string companyId, string branchId, string dateFrom, string dateTo, string supplierId)
        {
            try
            {
                if (companyId == "null")
                {
                    companyId = "";
                }
                if (branchId == "null")
                {
                    branchId = "";
                }
                if (dateFrom == "null")
                {
                    dateFrom = "";
                }
                if (dateTo == "null")
                {
                    dateTo = "";
                }
                if (supplierId == "null")
                {
                    supplierId = "";
                }
                if (!string.IsNullOrEmpty(dateFrom))
                {
                    DateTime? dfrom = Convert.ToDateTime(dateFrom);
                    dfrom = new DateTime(dfrom.Value.Year, dfrom.Value.Month, dfrom.Value.Day, 0, 0, 0);
                    dateFrom = dfrom.Value.ToString(CultureInfo.InvariantCulture);
                }
                if (!string.IsNullOrEmpty(dateTo))
                {
                    DateTime? dto = Convert.ToDateTime(dateTo);
                    dto = new DateTime(dto.Value.Year, dto.Value.Month, dto.Value.Day, 23, 59, 59);
                    dateTo = dto.Value.ToString(CultureInfo.InvariantCulture);
                }
                IEnumerable<MobileShopPurchaseDetailViewModel> purchaseDetails = new List<MobileShopPurchaseDetailViewModel>();
                if (!string.IsNullOrEmpty(companyId))
                {
                    purchaseDetails = Mapper.Map<IEnumerable<MobileShopPurchaseDetailViewModel>>(_rawSqlService.GetAllPurchaseDetail(companyId, branchId, dateFrom, dateTo, supplierId));
                }
                ReportDataSource rpt = new ReportDataSource("PurchaseDetail", purchaseDetails);
                RdlcReportViewerWithDate.reportDataSource = rpt;
                string rPath = "RdlcReport/RptPurchaseList.rdlc";
                Response.Redirect("~/ReportViewer/RdlcReportViewerWithDate.aspx?rPath=" + rPath + "&dfrom=" + dateFrom + "&dto=" + dateTo + "&companyId=" + companyId + "&branchId=" + branchId);
                return View();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult ReportPurchaseMasterDetail(string companyId, string branchId, string purchaseId)
        {
            try
            {
                var master = Mapper.Map<IEnumerable<PurchaseViewModelForReport>>(_purchaseService.GetAllForReport(purchaseId));
                var detail = Mapper.Map<IEnumerable<PurchaseDetailViewModelForReport>>(_purchaseService.GetAllPurchaseDetailbyMasterIdForReport(purchaseId));
                ReportDataSource rpt1 = new ReportDataSource("Purchase", master);
                ReportDataSource rpt2 = new ReportDataSource("PurchaseDetail", detail);
                List<ReportDataSource> rptl = new List<ReportDataSource> { rpt1, rpt2 };
                RdlcReportViewerMultipleDataSet.reportDataSource = rptl;
                string rPath = "RdlcReport/RptPurchaseInvoice.rdlc";
                Response.Redirect("~/ReportViewer/RdlcReportViewerMultipleDataSet.aspx?rPath=" + rPath + "&companyId=" + companyId + "&branchId=" + branchId);
                return View();
            }
            catch (Exception ex)
            {
                return JavaScript($"ShowResult('{ex.Message}','failure')");
            }
        }

        #endregion
    }
}

WebUI/Areas/APanel/Views/MobileShopPurchase/PurchaseList.cshtml
@model IEnumerable<Library.ViewModel.Inventory.Purchases.MobileShopPurchaseDetailViewModel>
@using ERP.WebUI.Html
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-lg-12">
        <a href="/APanel/MobileShopPurchase/PurchaseSummary" class="btn btn-bg pull-right top-button-back" role="button">Back</a>
        <h4 class="page-header">Purchase Information</h4>
    </div>
</div>
@using (Html.BeginForm("PurchaseList", "MobileShopPurchase", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label   mendatory">Company</label>
                @Html.SimpleDropDown("companyId", "/APanel/Company/GetCompanyList/", new { @class = "form-control", data_val = "true", data_val_required = "Company is required" })
                @Html.ValidationMessage("companyId", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label   mendatory" title="From date">From date</label>
                @Html.DatePicker("dateFrom", new { @class = "form-control", data_val = "true", data_val_required = "this is required" })
                @Html.ValidationMessage("dateFrom", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label  ">Branch</label>
                @Html.CascadingDropDown("branchId", "/APanel/Branch/GetBranchList/", "companyId", new { @class = "form-control" })
                @Html.ValidationMessage("branchId", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label   mendatory">To date</label>
                @Html.DatePicker("dateTo", new { @class = "form-control", data_val = "true", data_val_required = "this is required" })
                @Html.ValidationMessage("dateTo", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label   ">Supplier</label>
                @Html.SimpleDropDown("supplierId", "/Supplier/GetSupplierList", new { @class = "form-control" })
            </div>
            <div class="form-group ">
                <div class="submit-button">
                    <button type="submit" class="btn btn-bg">Show</button>
                    @Html.ActionLink("Report", "RdlcReportPurchaseList", "MobileShopPurchase", new { target = "_blank", id = "btnReport", @class = "btn btn-bg pull-middle" })
                    <input type="button" value="Clear" class="btn btn-warning" id="btnClear" />
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead class="thead-heading">
                            <tr>
                                <th>Purchase No.</th>
                                <th>Purchase Date</th>
                                <th>Supplier Name</th>
                                <th>Product Name</th>
                                <th>Purchase Price</th>
                                <th>Sales Price</th>
                                <th>Total Quantity</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PurchaseId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PurchaseDetailDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SupplierName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProductName)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.PurchasePrice)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.SalePrice)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.TotalAmount)
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                        <tfoot>
                             <tr class="text-right font-bold">
                                <td colspan="6">Total:</td>
                                <td>@Html.Raw(Model.Sum(x => Math.Round(x.Quantity, 2)))</td>
                                <td>@Html.Raw(Model.Sum(x => Math.Round(x.TotalAmount, 2)))</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            var dateFrom = getUrlVars()["dateFrom"];
            $("#dateFrom").val(dateFrom);
            var dateTo = getUrlVars()["dateTo"];
            $("#dateTo").val(dateTo);
        });



        $("#btnReport").click(function () {
            var companyId = $('#companyId').val();
            var branchId = $('#branchId').val();
            var dateFrom = $('#dateFrom').val();
            var dateTo = $('#dateTo').val();
            var supplierId = $('#supplierId').val();
            this.href = this.href.split('?')[0] + '?companyId=' + companyId
                + '&branchId=' + branchId
                + '&dateFrom=' + dateFrom
                + '&dateTo=' + dateTo
                + '&supplierId=' + supplierId;
        });

        $("#btnClear").on("click", function () {
            $("#companyId").val('').trigger("change");
            $("#branchId").val('').trigger("change");
            $("#supplierId").val('').trigger("change");
            $("#dateFrom").val('').trigger("change");
            $("#dateTo").val('').trigger("change");
        });
    </script>
}

WebUI/Areas/APanel/Views/MobileShopPurchase/PurchaseSummary.cshtml
@model IEnumerable<Library.ViewModel.Inventory.Purchases.MobileShopPurchaseViewModel>
@using ERP.WebUI.Html
@{
    ViewBag.Title = "PurchaseSummary";
}
<div class="row">
    <div class="col-lg-12">
        <a href="/APanel" class="btn btn-bg pull-right top-button-back" role="button">Back</a>
        <h4 class="page-header">Purchase Information</h4>
    </div>
</div>
@using (Html.BeginForm("PurchaseSummary", "MobileShopPurchase", FormMethod.Get, new { @id = "SearchForm" }))
{
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label   mendatory">Company</label>
                @Html.SimpleDropDown("companyId", "/APanel/Company/GetCompanyList/", new { @class = "form-control", data_val = "true", data_val_required = "This is required" })
                @Html.ValidationMessage("companyId", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label   mendatory" title="From date">From date</label>
                @Html.DatePicker("dateFrom", new { @class = "form-control", data_val = "true", data_val_required = "This is required" })
                @Html.ValidationMessage("dateFrom", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label  ">Branch</label>
                @Html.CascadingDropDown("branchId", "/APanel/Branch/GetBranchList/", "companyId", new { @class = "form-control" })
                @Html.ValidationMessage("branchId", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label   mendatory">To date</label>
                @Html.DatePicker("dateTo", new { @class = "form-control", data_val = "true", data_val_required = "This is required" })
                @Html.ValidationMessage("dateTo", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label   ">Supplier</label>
                @Html.SimpleDropDown("supplierId", "/Supplier/GetSupplierList", new { @class = "form-control" })
            </div>
            <div class="form-group ">
                <div class="submit-button">
                    <button type="submit" class="btn btn-bg">Show</button>
                    @Html.ActionLink("Report", "RdlcReportPurchaseSummary", "MobileShopPurchase", new { target = "_blank", id = "btnReport", @class = "btn btn-bg pull-middle" })
                    @Html.ActionLink("Detail Report", "PurchaseList", "MobileShopPurchase", new { @class = "btn btn-bg pull-middle" })
                    <input type="button" value="Clear" class="btn btn-warning" id="btnClear" />
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead class="thead-heading">
                            <tr>
                                <th>Purchase No.</th>
                                <th>Purchase Date</th>
                                <th>Supplier Name</th>
                                <th>Total Quantity</th>
                                <th>Total Amount</th>
                                <th>Memo Discount</th>
                                <th>Net Amount</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PurchaseDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SupplierName)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.TotalQuantity)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.TotalAmount)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.MemoWiseDiscount)
                                        </td>
                                        <td class="text-right">
                                            @Html.DisplayFor(modelItem => item.NetAmount)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Report ", "ReportPurchaseMasterDetail", "MobileShopPurchase", new { companyId = item.CompanyId, branchId = item.BranchId, purchaseId = item.Id }, new { target = "_blank", @class = "btn-sm btn-bg fa fa-edit" })
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                        <tfoot>
                            @if (Model != null && Model.Any())
                            {
                                 <tr class="text-right font-bold">
                                    <td colspan="3">Total:</td>
                                    <td>@Html.Raw(Model.Sum(x => Math.Round(x.TotalQuantity, 2)))</td>
                                    <td>@Html.Raw(Model.Sum(x => Math.Round(x.TotalAmount, 2)))</td>
                                    <td>@Html.Raw(Model.Sum(x => Math.Round(x.MemoWiseDiscount, 2)))</td>
                                    <td>@Html.Raw(Model.Sum(x => Math.Round(x.NetAmount, 2)))</td>
                                    <td></td>
                                </tr>
                            }
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            var dateFrom = getUrlVars()["dateFrom"];
            $("#dateFrom").val(dateFrom);
            var dateTo = getUrlVars()["dateTo"];
            $("#dateTo").val(dateTo);
        });

        $("#btnReport").click(function () {
            var companyId = $('#companyId').val();
            var branchId = $('#branchId').val();
            var dateFrom = $('#dateFrom').val();
            var dateTo = $('#dateTo').val();
            var supplierId = $('#supplierId').val();
            this.href = this.href.split('?')[0] + '?companyId=' + companyId
                + '&branchId=' + branchId
                + '&dateFrom=' + dateFrom
                + '&dateTo=' + dateTo
                + '&supplierId=' + supplierId;
        });

        $("#btnClear").on("click", function () {
            $("#companyId").val('').trigger("change");
            $("#branchId").val('').trigger("change");
            $("#supplierId").val('').trigger("change");
            $("#dateFrom").val('').trigger("change");
            $("#dateTo").val('').trigger("change");
        });
    </script>
}